FROM node:20-alpine

WORKDIR /app

RUN apk add --no-cache libc6-compat

ENV NEXT_TELEMETRY_DISABLED=1
ENV PORT=3000

ARG NEXT_PUBLIC_BACKEND_URL=https://backend-tizon-backend.vtufai.easypanel.host/api/v1
ARG NEXT_PUBLIC_SEND_EMAIL_WEBHOOK=
ARG NEXT_PUBLIC_ROBOFLOW_PUBLISHABLE_KEY=

ENV NEXT_PUBLIC_BACKEND_URL=$NEXT_PUBLIC_BACKEND_URL
ENV NEXT_PUBLIC_SEND_EMAIL_WEBHOOK=$NEXT_PUBLIC_SEND_EMAIL_WEBHOOK
ENV NEXT_PUBLIC_ROBOFLOW_PUBLISHABLE_KEY=$NEXT_PUBLIC_ROBOFLOW_PUBLISHABLE_KEY

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

ENV NODE_ENV=production

EXPOSE 3000

CMD ["npm", "run", "start", "--", "-H", "0.0.0.0", "-p", "3000"]
